### ISSUE TITLE
Display stock name instead of code/shortname (enhancement)

### ISSUE THREAD

**Issue by GLLM** [niteshpatel/ministocks#13]
For many stocks (french at least), you cannot see the name of the stock but only the code (or the short name).

Seeing the actual stock name would be much better !

Thanks

**Comment by niteshpatel** [comment]
Not sure if this is still an issue, custom names are supported on a per stock basis.  @GLLM if this is still an issue let me know a bit more about your requirement and I'll reopen (appreciate this is an old issue :/)
