### ISSUE TITLE
No option to add stocks.

### ISSUE THREAD

**Issue by stanfeig** [niteshpatel/ministocks#22]
I switched to OnePlus One phone. Installed Ministocks which worked well, but for only one day. I uninstalled and re-installed. Every time I install Ministocks, it opens showing the Dow Jones Industrial Average, but there is no option to add stocks to the portfolio. There is no "Settings" icon or menu item.

**Comment by niteshpatel** [comment]
When you touch the left side of the widget, does it not go into the 
menu? What do you see?

**Comment by niteshpatel** [comment]
Unable to recreate, and no response, closing as obsolete.
