### ISSUE TITLE
Comment removed

### ISSUE THREAD

**Issue by pizzamaker** [niteshpatel/ministocks#31]

**Comment by niteshpatel** [comment]
Hi there,

 

Sorry for the late response.

 

Thanks I will look into it, does it take long?

 

Kind regards

 

-Nitesh

**Comment by pizzamaker** [comment]
Hi there! It depends, really. But the upside is that your app is available in more places, for a free software audience :)

Here's how to: https://f-droid.org/contribute/

**Comment by niteshpatel** [comment]
Alright thanks, I will look into it.
