### ISSUE TITLE
Decimal separator in portfolios price fields

### ISSUE THREAD

**Issue by Nicknag** [niteshpatel/ministocks#35]
Hi,
the decimal separator of the current language setting is not accepted in the portfolios price fields.

In my language the decimal separator is a comma. But I can only input the prices using a dot.

A comma is used corectly to show prices on all places in the app.

Regards Nick

**Comment by niteshpatel** [comment]
I will look into this.

**Comment by niteshpatel** [comment]
This was resolved in version-66
