### ISSUE TITLE
Ministock does not work on Note8

### ISSUE THREAD

**Issue by ntrpriz1701e** [niteshpatel/ministocks#51]
Been using the app for years. Just installed on my Note8 and what was working on every phone, including my S7 Edge now aborts every time I try to add the widget to a screen "Ministock has Stopped".

**Comment by niteshpatel** [comment]
Thanks for letting me know – I hope to roll a fix in the next couple of days.

 

-Nitesh

**Comment by Kbehr312** [comment]
I also have had this problem on my S8+. The widget will no longer automatically refresh at the set intervals.

**Comment by niteshpatel** [comment]
Is this still an issue?

**Comment by ntrpriz1701e** [comment]
no resolved very quicklt after original email. Then recently stopped working again - but that was fixed with your latest update about a week or so ago - All is well - thank you for the quick response.

**Comment by niteshpatel** [comment]
Not an issue atm.
