### ISSUE TITLE
ministocks stoped updating stocks

### ISSUE THREAD

**Issue by roeesa** [niteshpatel/ministocks#56]
checked on top one-plus 2
with stocks from Nasdaq / NYSE

**Comment by mandroidpro** [comment]
It is because it uses an api that doesn't work. Use this app instead it is better: https://play.google.com/store/apps/details?id=com.github.premnirmal.tickerwidget also open source https://github.com/premnirmal/StockTicker

**Comment by mharfuch** [comment]
Hi there! I'll just subscribe in case this gets fixed. I love this widget.
Big hug

**Comment by woj-tek** [comment]
@mandroidpro while it seems to look better it also doesn't work...

hopefully ministock will be fixed soon.

**Comment by mandroidpro** [comment]
@woj-tek it does work. Some symbols don't work with stockticker, But most US symbols work on that app. It is also has a WAY better UI than this app :)

**Comment by woj-tek** [comment]
OT: Not everyone lives in the US ;-) and some people are more interested in currencies.

**Comment by mandroidpro** [comment]
@woj-tek you're just too picky 😂 . I guess you can just use a web browser

**Comment by simo1994** [comment]
@mandroidpro I don't think you're helping anyone by promoting another app and then telling picky people should just stick to a web browser.

That app should be license compatible to this one, so the developer could look that code to find a partial solution for US stocks.

Apparently, Yahoo Finance is changing things. I don't know if this is still relevant, but I would suggest the developer to look here https://github.com/c0redumb/yahoo_quote_download for a possible fix.

Another alternative could be getting quotes from YQL -- but that requires an API key.

**Comment by woj-tek** [comment]
Purely for stock information there is also robinhood: https://github.com/sanko/Robinhood/blob/master/Quote.md

**Comment by mandroidpro** [comment]
StockTicker frankly is a better app, and it is license compatible :) (they both use the MIT license).

**Comment by mandroidpro** [comment]
I too hope that ministocks finds a solution soon. But until then, StockTicker is a savior for most users

**Comment by muziofg** [comment]
this tiny app deserves to be survive

I'll propose two solution:

1) yahoo has discontinued the service because "this service is being used in violation of the Yahoo Terms of Service" 
Ok, well, then if I use for years this service in non-legal circustances we can use in the same way the new api:

now we can retreive multiple realtime stock quotes in json format, a simple example in python/pandas:

data=pd.read_json("https://query2.finance.yahoo.com/v7/finance/quote?symbols=NVDA,INTC,AMD")
for i in range(len(data['quoteResponse']['result'])):
    print (data['quoteResponse']['result'][i]['symbol'],data['quoteResponse']['result'][i]['regularMarketOpen'])

no crumb-mechanism is required

source: https://github.com/pilwon/node-yahoo-finance/issues/43

2) I have found https://www.alphavantage.co/ that provide realtime data (also in csv)  
An api key is required but it's free

**Comment by mandroidpro** [comment]
@woj-tek 

>Purely for stock information there is also robinhood: 
Didn't you say "_OT: Not everyone lives in the US ;-) and some people are more interested in currencies._" ? 😂  robinhood will give prices for US stocks only ;-)

**Comment by niteshpatel** [comment]
For the time being I think I will use: https://iextrading.com/developer/docs/ 

I will look at the other alternatives proposed in this thread later.  My priority is to get something working at least in the short term and then spend some time trying to find the best long term solution.

**Comment by niteshpatel** [comment]
In the meantime, anyone want to contribute I will happily look at any pull requests that make test\java\nitezh\ministock\dataaccess\YahooStockQuoteRepositoryTests.java (or at least an equivalent version of the module) but from another provider work.

**Comment by keverets** [comment]
The new version with iextrading as the source still does not update for me.

**Comment by niteshpatel** [comment]
Should be fixed in version 72
