### ISSUE TITLE
Application force closing on widget add

### ISSUE THREAD

**Issue by Takha25** [niteshpatel/ministocks#68]
This is very useful widget and I like it. Yesterday I tried to install the widget from Google Play on new Samsung Galaxy Note 8 and it failed. The same error happened on emulator. Locale on device is English-UK. After investigation, I found that crash is in class WidgetView.java, method getTimeStamp().

Fatal error: java.lang.ArrayIndexOutOfBoundsException: length=1; index=1 
The crash happens in line:
`String fullDate = parts[0] + " " + parts[1];`

I commented out entire "if" block and the error disappeared.

**Comment by niteshpatel** [comment]
Hi can you tell me what language and orientation you have the widget in, portrait or landscape?

**Comment by Takha25** [comment]
Hi, I have portrait orientation.

**Comment by niteshpatel** [comment]
What language

**Comment by Takha25** [comment]
English
