### ISSUE TITLE
fetching data seems stopped working

### ISSUE THREAD

**Issue by muziofg** [niteshpatel/ministocks#80]
today fetching data seems stopped working, I'm unable to see fresh updated stocks prices (nor automatic, nor manual)
API hasn't stopped working, for example I can query with success the url 

"https://query1.finance.yahoo.com/v7/finance/quote?fields=symbol,regularMarketPrice,regularMarketChange,regularMarketChangePercent,regularMarketVolume,shortName,longName&symbols=META";

I have also tried to install from play store to a clean device a new instance of this app and trying to fetch data for a single ticker without success

I have tried to reproduce the behavior with this simple java SE software, but unfortunately it works for me

```

import java.net.URL;
import java.net.URLConnection;
import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStream;
import java.io.InputStreamReader;

class StockData{  
    public static void main(String args[]) throws Exception{
        String url = "https://query1.finance.yahoo.com/v7/finance/quote?fields=symbol,regularMarketPrice,regularMarketChange,regularMarketChangePercent,regularMarketVolume,shortName,longName&symbols=META";
        URLConnection connection = new URL(url).openConnection();
        connection.setConnectTimeout(30000);
        connection.setReadTimeout(60000);
        BufferedReader r = new BufferedReader(new InputStreamReader(connection.getInputStream()));  
        String line;
            while ((line = r.readLine()) != null) {
            System.out.println(line);  
        }
    }  
}  
```

I don't know if, for example, on android platform URLConnection has a  different (and banned) user agent

**Comment by enricodevtest** [comment]
I just wanted to confirm that you are not the only person experiencing this problem. The price updates are not happening right now for me too.

**Comment by mossi1960** [comment]
Since 2 days the price updates are not happening for me too.

**Comment by fabiorauber** [comment]
Mine stopped working as well.

**Comment by niteshpatel** [comment]
@muziofg looks to be the user agent as you guessed.  have pushed an update but Google has put it under view, not sure how long it takes.  hopefully that fixes it.  thanks for putting effort in to help diagnose

**Comment by niteshpatel** [comment]
This should be fixed now.
 
Note that fixing this stuff requires a lot of effort as often not only the
logic needs to be fixed, but updated versions of the programs I used for
development need to be setup (since this app is not updated frequently) and
configured.
 
If you appreciate the effort please put a 5 star review on the Play store.  
 
Thanks

**Comment by niteshpatel** [comment]
This should be fixed now.
 
Note that fixing this stuff requires a lot of effort as often not only the
logic needs to be fixed, but updated versions of the programs I used for
development need to be setup (since this app is not updated frequently) and
configured.
 
If you appreciate the effort please put a 5 star review on the Play store.  
 
Thanks

**Comment by niteshpatel** [comment]
This should be fixed now.
 
Note that fixing this stuff requires a lot of effort as often not only the
logic needs to be fixed, but updated versions of the programs I used for
development need to be setup (since this app is not updated frequently) and
configured.
 
If you appreciate the effort please put a 5 star review on the Play store.  
 
Thanks

**Comment by bencew** [comment]
Thanks for the update, Nitesh!
Are you going to initiate to update the F-droid version, too? I've the app installed from there

**Comment by niteshpatel** [comment]
Hi benecew – probably not.  I didn’t load it there in the first place (not sure how)?

**Comment by bencew** [comment]
Weird, the F-Droid page is linked here in the readme

**Comment by niteshpatel** [comment]
I believe F-Droid will pull it automatically at some point.

**Comment by muziofg** [comment]
> This should be fixed now. Note that fixing this stuff requires a lot of effort as often not only the logic needs to be fixed, but updated versions of the programs I used for development need to be setup (since this app is not updated frequently) and configured.


I have seen it (and recognize the effort) by the last commit, now app requires at least Android 6.0 (plus some minimal changes, like enumerated property values), you can update the description on github/stores page to avoid misunderstandings.

In the commit I also have seen that now the app idenfing itself as "Ministocks - Stocks Widget". That's a honest choice, but exposes Ministocks to identification/ban risks, I was thinking more like an identification as Chrome/Firefox

Many thanks to you for the fast bugfixing

**Comment by niteshpatel** [comment]
Ah good points, will make a note.  thank you

**Comment by morganchristiansson** [comment]
Maybe automating releases to Play Store / F-Droid using Github Actions ís a good idea?

**Comment by niteshpatel** [comment]
> Maybe automating releases to Play Store / F-Droid using Github Actions ís a good idea?

The app is updated too infrequently for the effort to maintain this to be worthwhile.  Also releasing to play store often includes additional steps some of which are based on Google policy changes etc. that frequently require manual unpredictable steps.

**Comment by morganchristiansson** [comment]
Having a pipeline that is not dependent on local tooling would make infrequent releases easier. Just a friendly suggestion.

**Comment by niteshpatel** [comment]
Appreciate the suggestion but totally disagree!
